### ISSUE TITLE
Where did you found the hidden files?

### ISSUE THREAD

**Issue by ivorpad** [Jinsung-L/install-macos-high-sierra#2]
These two: `BaseSystem.dmg` and `BaseSystem.chunklist`

I can't for the life of me find these two files.

**Comment by Jinsung-L** [comment]
I downloaded the files from this URL `http://swcdn.apple.com/content/downloads/04/61/091-34298/almpfkbhyxnsgbxxqhoqo7sb40w3uip0wk/BaseSystem.dmg` and `http://swcdn.apple.com/content/downloads/04/61/091-34298/almpfkbhyxnsgbxxqhoqo7sb40w3uip0wk/BaseSystem.chunklist`
But now the links seem unavailable. Open the log window then get the appropriate URL for your case. The log will say something like this: `Retrying http://swcdn.apple.com/content/downloads/04/61/091-34298/almpfkbhyxnsgbxxqhoqo7sb40w3uip0wk/InstallESDDmg.pkg after 1 failure(s)`
Just replace the last part of the URL with the filename you want to download.
